### ISSUE TITLE
Add support to pass OSRM configurations in the `evaluate_solution` function

### ISSUE THREAD

**Issue by fillipe-gsm** [loggi/loggibud#20]
When running the OSRM server with different configurations than the default ones, we can usually call the function with something like:

```python
from loggibud.v1.distances import calculate_distance_matrix_m, OSRMConfig

config = OSRMConfig(host="new-address")
distance_matrix = calculate_distance_matrix_m(points, config)
```

However, in the `evaluation_solution` function from `loggibud.v1.eval.task1`, we are stuck with the default parameters as it has no way of receiving this `config` variable:

![image](https://user-images.githubusercontent.com/10814987/119906665-072cbe00-bf25-11eb-81f0-dd1b2d236e23.png)

I created this issue for us to determine a good approach for handling it.

Maybe simply add this `config` variable as an input parameter to `evaluate_solution`?

**Comment by gabisurita** [comment]
Adding the config as an additional parameter sounds reasonable.
