### ISSUE TITLE
Broken links

### ISSUE THREAD

**Issue by joaorochajr** [loggi/loggibud#7]
There are some broken links in the documentation:
  - The link  to "generation pipeline documentation" is broken
  - The link  to "OSRM detailed documentation" is also broken

To reproduce the issue, go to page "https://github.com/loggi/loggibud/blob/master/docs/quickstart.md" and clink on the cited links.

**Comment by gabisurita** [comment]
Fixed by https://github.com/loggi/loggibud/commit/610bd2b59c7de7911e3f82fc6df7f2800f880cd5

Thanks for the report.
